port: 3000
lang: "ja-JP"
debug: true
logformat: "${pid} [${ip}]:${port} ${status} - ${method} ${path}\n"
root: /api/v1/
token: []
bodylimit: 1024
db:
  type: bbolt
  uri: bbolt.db
  name: octane
storage:
  type: local
  uri: ./uploads
  housekeeping: 
